### ISSUE TITLE
examples/v2/gke/jinja: update fails

### ISSUE THREAD

**Issue by leo-baltus** [GoogleCloudPlatform/deploymentmanager-samples#17]
Not sure if this is the right place or way to report this, but here goes:
```
cd deploymentmanager-samples/examples/v2/gke/jinja
gcloud deployment-manager deployments create cluster --config cluster.yaml
```
edit ./cluster.jinja.schema (change  number of nodes from 4 to 2)

```
gcloud deployment-manager deployments update cluster --config cluster.yaml
The fingerprint of the deployment is tv3Y40Z8rRXCnMy8jxgj8A==
Waiting for update [operation-1499161746927-5537acb62ed98-16269ef3-6106d074]...failed.
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1499161746927-5537acb62ed98-16269ef3-6106d074]: errors:
- code: RESOURCE_ERROR
  location: /deployments/cluster/resources/cluster-leo1
  message: '{"ResourceType":"container.v1.cluster","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Invalid
    JSON payload received. Unknown name \"cluster\": Cannot find field.","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"description":"Invalid
    JSON payload received. Unknown name \"cluster\": Cannot find field."}]}],"statusMessage":"Bad
    Request","requestPath":"https://container.googleapis.com/v1/projects/102xyzxyz238/zones/europe-west1-b/clusters/cluster-leo1"}}'
```
The same thing happens when doing `...update cluster --config cluster.yaml --preview` followed by `... update cluster`

**Comment by nfirvine** [comment]
This bug: 
https://stackoverflow.com/questions/44525692/google-cloud-deployment-manager-update-container-cluster
https://issuetracker.google.com/issues/38131324

**Comment by davidebelloni** [comment]
Hi,
I have the same problem

**Comment by munutzer** [comment]
I'm currently working on supporting cluster updates through DM. Estimating one month until more update support is available.

**Comment by munutzer** [comment]
I have updated the cluster type so that changing the initialNodeCount property in the DM config will resize the node pool. Note that the initialNodeCount property change won't be reflected in the cluster API (initialNodeCount property stores initial, not current size), but you can see the resize by looking at the underlying managed instance group:

$ gcloud deployment-manager deployments create cluster-resize --template https://raw.githubusercontent.com/GoogleCloudPlatform/deploymentmanager-samples/master/examples/v2/gke/jinja/cluster.jinja --properties zone:us-central1-a,initialNodeCount:2

$ gcloud compute instance-groups managed list
NAME                                                LOCATION       SCOPE  BASE_INSTANCE_NAME                              SIZE  TARGET_SIZE  INSTANCE_TEMPLATE                               AUTOSCALED
gke-cluster-resize-clust-default-pool-05527e5c-grp  us-central1-a  zone   gke-cluster-resize-clust-default-pool-05527e5c  **2     2**            gke-cluster-resize-clust-default-pool-05527e5c  no

$ gcloud deployment-manager deployments update cluster-resize --template https://raw.githubusercontent.com/GoogleCloudPlatform/deploymentmanager-samples/master/examples/v2/gke/jinja/cluster.jinja --properties zone:us-central1-a,initialNodeCount:3

$ gcloud compute instance-groups managed list                                                                                                                                       NAME                                                LOCATION       SCOPE  BASE_INSTANCE_NAME                              SIZE  TARGET_SIZE  INSTANCE_TEMPLATE                               AUTOSCALED
gke-cluster-resize-clust-default-pool-05527e5c-grp  us-central1-a  zone   gke-cluster-resize-clust-default-pool-05527e5c  **3     3**            gke-cluster-resize-clust-default-pool-05527e5c  no
