### ISSUE TITLE
Error in project creation

### ISSUE THREAD

**Issue by qibin-google** [GoogleCloudPlatform/deploymentmanager-samples#45]
I used the following yaml to create a project

imports:
\- path: project.py
resources:
\- name: qibinzhou-test-dm-20171009
  type: project.py
  properties:
    organization-id: "OUR_ORGANIZATION_ID"
    billing-account-name: billingAccounts/OUR_BILLING_ACCOUNT
    \- compute.googleapis.com
    \- deploymentmanager.googleapis.com
    \- pubsub.googleapis.com
    \- storage-component.googleapis.com
    \- monitoring.googleapis.com
    \- logging.googleapis.com
    service-accounts:
    \- qibinzhou-test-dm-1
    bucket-export-settings:
      create-bucket: true
    iam-policy:
      bindings:
      \- role: roles/owner
        members:
        \- serviceAccount:DM_CREATE_PROJECT_ID@cloudservices.gserviceaccount.com
        \- user:MY_ACCOUNT

And I got the following error:

ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1507647406494-55b32841c5131-8e991c04-414d4a33]: errors:
- code: RESOURCE_ERROR
  location: /deployments/qibinzhou-test-dm-1/resources/qibinzhou-test-dm-20171009
  message: '{"ResourceType":"cloudresourcemanager.v1.project","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"User is not authorized.","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.ResourceInfo","resourceType":"ORGANIZATION","resourceName":"OrganizationId{toLong=<organization ID>,getResourceType=ORGANIZATION}"}],"statusMessage":"Forbidden","requestPath":"https://cloudresourcemanager.googleapis.com/v1/projects","httpMethod":"POST"}}'

I have set project as the DM create project in gcloud config. But I set my own account, instead of the cloudservices service account or the so-called DM Service Account, in gcloud config. I don't quite understand how to use the DM Service Account. It is an internal account and has no external keys that can be generated. Then we cannot activate it on our local machine. 

Thanks,

Qibin

**Comment by katyp** [comment]
Hi Qibin,

A few notes. First, your pasted yaml is missing the "apis" key:

apis:
- compute.googleapis.com
- deploymentmanager.googleapis.com
- pubsub.googleapis.com
- storage-component.googleapis.com
- monitoring.googleapis.com
- logging.googleapis.com

But I assume that's a copy/paste error.

It sounds like you are creating the deployment from "DM create project", in which case it is correct to give that service account owner access to your new project. You do not need to log in as the DM service account in order to use it; it is automatically used by DM on your behalf every time DM calls an underlying API on your behalf.

The error message indicates to me that you may not have given your dm robot permission within your organization to create a project. This is step 5 in the readme:

https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/examples/v2/project_creation

Can you verify for me that you've taken this step and let me know if you are still seeing failures?

Thanks!
-Katy

**Comment by krwenholz** [comment]
Hi @qibin-google,

I'm closing this for now, but please feel free to reopen it if you need any more help.
