### ISSUE TITLE
deleting deployment without deleting network

### ISSUE THREAD

**Issue by LukasBlank** [GoogleCloudPlatform/deploymentmanager-samples#481]
I followed https://www.kubeflow.org/docs/gke/deploy/deploy-cli/ and had an error because i had no default network. Afterwards i found this https://www.kubeflow.org/docs/gke/troubleshooting-gke/#legacy-networks-are-not-supported and tried the same steps. This creates a new network, and gave me an error because there already was a network with the name i selected. Now this is my problem: the deployment manager is still showing me the deployment which failed but if i want to delete the deployment he will try to delete the referenced network aswell, even tough this one existed before the creation of the deployment and was not created by it. 
Is there a way to delete the failed deployment without deleting the referenced network aswell?

**Comment by ocsig** [comment]
One quick solution is:
Deletion policy: abandon.

This will remove the resource from the deployment instead of deletion. If you delete the entire deployment, it will just abandon everyting.:

`gcloud deployment-manager deployments delete DEPLOYMENT_NAME  --delete-policy=abandon`
or
`gcloud deployment-manager deployments update DEPLOYMENT_NAME  --delete-policy=abandon --config=myconfig.yaml`
